## Assingment 2

### 1. Create 2D array and get sum of diagonal elements.

In [1]:
import numpy as np
#creating a array
arr = np.array([[1, 2, 3, 4], [4, 5, 6, 1], [1, 4, 7, 6], [9, 3, 6, 4]])
print("Array:\n",arr)
#storing all the diagonal elements in a different array
arr_diagonal_element = arr.diagonal()    
print("\nDiagonal element:",arr_diagonal_element) 
print("\nSum of Diagonal elements:",np.sum(arr_diagonal_element))

Array:
 [[1 2 3 4]
 [4 5 6 1]
 [1 4 7 6]
 [9 3 6 4]]

Diagonal element: [1 5 7 4]

Sum of Diagonal elements: 17


### 2. Slice the 2D array into multiple 1D arrays by rows.



In [2]:
#slicing the arrays row-wise
arr1 = np.split(arr,4)
print("Sliced array:",arr1)

Sliced array: [array([[1, 2, 3, 4]]), array([[4, 5, 6, 1]]), array([[1, 4, 7, 6]]), array([[9, 3, 6, 4]])]


### 3. Print the array element from all 1D array where index is even number and store it in another array.

In [3]:
arr2 = np.concatenate(arr1)
arr2 = arr2.ravel()

#Creating a empty array
arr3 = np.empty(0, dtype=object)
print("Elements at even indexs:")
for i in range(1, len(arr2), 2):  
    arr3 = np.append(arr3,arr2[i])
print(arr3)

Elements at even indexs:
[2 4 5 1 4 6 3 4]


### 4. Take the all output arrays of step 3 and create 2-D array from that and print that array and also dimension of that array.

In [4]:
#reshaping the array and storing it in other array
arr4 = arr3.reshape(2,4)
print(arr4)
print("Shape of array:",arr4.shape)

[[2 4 5 1]
 [4 6 3 4]]
Shape of array: (2, 4)
